#version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.frontend
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules


